language: ruby
install:
  - sudo apt-get -y install linkchecker apache2 libicu-dev
  - gem install html-pipeline
  - gem install github-linguist
  - gem install github-markdown
  - gem install sanitize
  - gem install gemoji
  - gem install rinku

before_script:
  - sudo sed -i '/<\/VirtualHost/ i\ <Directory /var/www/html/>\n  AllowOverride All\n </Directory>' /etc/apache2/sites-enabled/*.conf
  - cp -r * /var/www/html/
  - service apache2 restart

script:
  - for f in $(find . -type '*.md') ; do
      $(gem contents html-pipeline | grep bin/html-pipeline) |
      sed s,https?://w3id.org/,http://localhost/,g> /tmp/index.html && 
      linkchecker /tmp/index.html || exit 1 ; done


