language: bash

before_install:  
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq install linkchecker apache2

before_script:
  - sudo sed -i '/<\/VirtualHost/ i\ <Directory /var/www/>\n  AllowOverride All\n </Directory>' /etc/apache2/sites-enabled/*
  - sudo sed -i "s/80/8080/g" /etc/apache2/sites-enabled/* /etc/apache2/ports.conf
  - sudo cp -r * /var/www/
  - sudo a2enmod rewrite
  - service apache2 restart
  - mkdir -p ~/.linkchecker
  - echo -e "[filtering]\nignorewarnings=http-moved-permanent" > ~/.linkchecker/linkcheckerrc

script:
  - tail -f /var/log/apache2/access.log & 
  - tail -f /var/log/apache2/error.log >&2 &
  - cat $(find . -name '*.md') | 
    grep https://w3id.org | 
    sed 's,.*https://w3id.org/,http://localhost:8080/,' |
    sed 's,[ )].*,,' | 
    linkchecker --stdin -r 0

after_script:
  - cat /var/log/apache2/access.log

after_failure:
  - cat /var/log/apache2/error.log

