language: bash
install:
  - sudo apt-get -y install linkchecker apache2

before_script:
  - sudo sed -i '/<\/VirtualHost/ i\ <Directory /var/www/>\n  AllowOverride All\n </Directory>' /etc/apache2/sites-enabled/*
  - sudo cp -r * /var/www/
  - service apache2 restart
  - mkdir -p ~/.linkchecker
  - echo -e "[filtering]\nignorewarnings=http-moved-permanent" > ~/.linkchecker/linkcheckerrc

script:
  - cat $(find . -name '*.md') | 
    grep https://w3id.org | 
    sed 's,.*https://w3id.org/,http://localhost/,' |
    sed 's,[ )].*,,' | 
    linkchecker --stdin -r 0


